#!/bin/bash

## Description: Run yarn inside the default theme directory
## Usage: theme [flags] [args]
## Example: "ddev theme install" or "ddev theme watch" or "ddev theme build"
## ExecRaw: true
## HostWorkingDir: true

if [ $1 = "watch" ]; then
    npm --prefix public/app/themes/bigfork run watch
elif [ $1 = "prod" ]; then
    npm --prefix public/app/themes/bigfork run prod
elif [ $1 = "build" ]; then
    npm --prefix public/app/themes/bigfork run prod
else
    npm --prefix public/app/themes/bigfork "$@"
fi

